name: lint
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint "src/js/*.js" --fix
      - name: Run Stylelint
        run: |
          npm init stylelint --yes
          npx stylelint "src/css/*.css" --fix
      - name: Run Json Lint
        run: npx jsonlint-cli "src/data/*.json" --fix
      - name: Run HTMLHint
        run: npx htmlhint "src/public/*.html" --fix
